# Generated by Django 5.1.7 on 2025-05-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
